### ISSUE TITLE
edits

### ISSUE THREAD

**Issue by pskeshu** [ndsystems/ndsystems.github.io#8]

**Comment by pskeshu** [comment]
pskeshu#9576 discord link in the site

nDsystems in the front page should read n-Dimensional Systems.

Try to include the existing logo somewhere.

Address: Goppanpally, Hyderabad, India.

**Comment by subindevs** [comment]
@pskeshu what do you mean by existing logo, the one that we used in previous website?

**Comment by pskeshu** [comment]
![logo](https://user-images.githubusercontent.com/7001840/107332441-30425380-6ada-11eb-9e44-5625789fa7fe.jpeg)
